title: Holiday Internet User's Page
description: "Explore my projects"
baseurl: "/hiu" 
url: "https://holidayinternetuser.github.io"

author:
  name: Holiday Internet User
  email: holidayinternetuser@protonmail.com
  bio: I like cats
  twitter_username: Holiday_I_User
  github_username: HolidayInternetUser

theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed

custom_css: |
  body {
      margin: 0;
      height: 100vh; /* Full height */
      background-color: blue; /* Blue background */
      color: white; /* Text color */
      display: flex; /* Center text */
      justify-content: center; /* Center horizontally */
      align-items: center; /* Center vertically */
      flex-direction: column; /* Stack elements vertically */
  }

  h1, p {
      text-align: center; /* Center text */
  }

social_links:
  twitter: https://x.com/Holiday_I_User
  github: https://github.com/HolidayInternetUser
