# _config.yml for GitHub Pages blog with a blue background

# Site settings
title: Holiday Internet User's Blog
description: "Explore my projects and thoughts"
baseurl: "/hiu" 
url: "https://holidayinternetuser.github.io"

# Author settings
author:
  name: Holiday Internet User
  email: holidayinternetuser@protonmail.com

# Appearance
theme: minima
plugins:
  - jekyll-feed

# Pagination settings
paginate: 5 # Number of posts per page
paginate_path: "/page:num/" # Path for pagination

# Custom CSS (this won't work natively but indicates your intention)
custom_css: |
  body {
      margin: 0;
      height: 100vh; /* Full height */
      background-color: blue; /* Blue background */
      color: white; /* Text color */
      display: flex; /* Center text */
      flex-direction: column; /* Stack elements vertically */
      align-items: center; /* Center horizontally */
      justify-content: center; /* Center vertically */
      font-family: Arial, sans-serif; /* Font style */
  }
  h1, h2 {
      color: white; /* Heading color */
  }
  a {
      color: yellow; /* Link color */
  }
  footer {
      margin-top: auto; /* Push footer to the bottom */
  }

# Social media settings (optional)
social_links:
  twitter: https://x.com/Holiday_I_User
  github: https://github.com/HolidayInternetUser
