title: Holiday Internet User's Page
description: "Explore my projects"
baseurl: "/hiu" 
url: "https://holidayinternetuser.github.io"

author:
  name: Holiday Internet User
  email: holidayinternetuser@protonmail.com
  bio: I like cats
  twitter_username: Holiday_I_User
  github_username: HolidayInternetUser

theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed


social_links:
  twitter: https://x.com/Holiday_I_User
  github: https://github.com/HolidayInternetUser
