# _config.yml for GitHub Pages blog

# Site settings
title: Holiday Internet User's Blog
description: "Explore my projects and thoughts"
baseurl: "/hiu" 
url: "https://holidayinternetuser.github.io"

# Author settings
author:
  name: Holiday Internet User
  email: holidayinternetuser@protonmail.com
  bio: I like cats
  twitter_username: Holiday_I_User
  github_username: HolidayInternetUser

# Appearance
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate # Enable pagination for blog posts

# Pagination settings
paginate: 5 # Number of posts per page
paginate_path: "/page:num/" # Path for pagination

# Social media settings (optional)
social_links:
  twitter: https://x.com/Holiday_I_User
  github: https://github.com/HolidayInternetUser
