title: "Holiday Internet User's Page"
description: "Explore my projects."
project1: "Webcam Viewer"
webcamviewer: "https://github.com/HolidayInternetUser/webcamviewer"
theme: "jekyll-theme-minimal"

name: "Holiday Internet User"
email: "h.i.u.contactemail@protonmail.com"
bio: "I like cats and tech."
github_username: "HolidayInternetUser"
youtube_username: "Holiday Internet User"
youtube_username2 : "Holiday Internet User Math and Physics"
youtube_username3: "Holiday Internet User Code"
x_username: "Holiday_I_User"

youtube: "https://www.youtube.com/@HolidayInternetUser"
youtube2: "https://www.youtube.com/@HolidayInternetUserMathPhysics"
youtube3: "https://www.youtube.com/@HolidayInternetUserCode"
x: "https://x.com/holidayinternetuser"
github: "https://github.com/HolidayInternetUser"

show_personal_info: true
