# _config.yml for a simple blog with a blue background

# Site settings
title: Holiday Internet User's Blog
description: "Explore my projects and thoughts"
baseurl: "/hiu" 
url: "https://holidayinternetuser.github.io"

# Author settings
author:
  name: Holiday Internet User
  email: holidayinternetuser@protonmail.com

# Appearance
theme: minima
plugins:
  - jekyll-feed
