# _config.yml for a simple blog with a blue background

# Site settings
title: Holiday Internet User's Blog
description: "Explore my projects and thoughts"
baseurl: "/hiu" 
url: "https://holidayinternetuser.github.io"

# Author settings
author:
  name: Holiday Internet User
  email: holidayinternetuser@protonmail.com

# Appearance
theme: minima
plugins:
  - jekyll-feed

# Pagination settings
paginate: 5 # Number of posts per page
paginate_path: "/page:num/" # Path for pagination

# Custom CSS (for blue background)
custom_css: |
  body {
    background-color: blue; /* Set the background color to blue */
    color: white; /* Set text color to white for visibility */
    font-family: Arial, sans-serif; /* Set font style */
    margin: 0; /* Remove default margin */
    padding: 20px; /* Add some padding */
  }
